SELECT DATABASE(); 
USE godb; 


LOAD DATA INFILE './go_class_data.csv' INTO TABLE GO_class  
FIELDS TERMINATED BY '\t' ENCLOSED BY '"'
IGNORE 1 LINES;

LOAD DATA INFILE './genes_data.csv' INTO TABLE Gene_gnprod  
FIELDS TERMINATED BY '\t' ENCLOSED BY '"'
IGNORE 1 LINES;

-- SET FOREIGN_KEY_CHECKS=1;
LOAD DATA INFILE './unique_annotations_data.csv' INTO TABLE Annotations  
FIELDS TERMINATED BY '\t' ENCLOSED BY '"'
IGNORE 1 LINES;
